from app.bot.keyboards.admin import (
    get_admin_cancel_keyboard,
    get_admin_categories_keyboard,
    get_admin_category_detail_keyboard,
    get_admin_category_select_keyboard,
    get_admin_dashboard_keyboard,
    get_admin_delete_confirm_keyboard,
    get_admin_recipe_actions_keyboard,
    get_admin_skip_cancel_keyboard,
)
from app.bot.keyboards.callbacks import (
    AdminActionCallback,
    CatalogNavCallback,
    CategorySearchCallback,
    FavoriteToggleCallback,
    FridgeActionCallback,
    LanguageSelectCallback,
    MainMenuCallback,
    PaginationCallback,
    RecipeMediaCallback,
    RecipeViewCallback,
    SearchModeCallback,
    SortToggleCallback,
)
from app.bot.keyboards.catalog import (
    get_recipe_view_keyboard,
    get_recipes_list_keyboard,
    get_search_results_keyboard,
    get_subcategories_keyboard,
    get_top_categories_keyboard,
)
from app.bot.keyboards.common import (
    get_back_keyboard,
    get_cancel_keyboard,
    get_language_keyboard,
    get_main_menu_keyboard,
    get_search_menu_keyboard,
)
from app.bot.keyboards.favorites import get_favorites_keyboard
from app.bot.keyboards.fridge import (
    get_fridge_cancel_keyboard,
    get_fridge_main_keyboard,
    get_fridge_match_results_keyboard,
)

__all__: list[str] = [
    "AdminActionCallback",
    "CatalogNavCallback",
    "CategorySearchCallback",
    "FavoriteToggleCallback",
    "FridgeActionCallback",
    "LanguageSelectCallback",
    "MainMenuCallback",
    "PaginationCallback",
    "RecipeMediaCallback",
    "RecipeViewCallback",
    "SearchModeCallback",
    "SortToggleCallback",
    "get_admin_cancel_keyboard",
    "get_admin_categories_keyboard",
    "get_admin_category_detail_keyboard",
    "get_admin_category_select_keyboard",
    "get_admin_dashboard_keyboard",
    "get_admin_delete_confirm_keyboard",
    "get_admin_recipe_actions_keyboard",
    "get_admin_skip_cancel_keyboard",
    "get_back_keyboard",
    "get_cancel_keyboard",
    "get_favorites_keyboard",
    "get_fridge_cancel_keyboard",
    "get_fridge_main_keyboard",
    "get_fridge_match_results_keyboard",
    "get_language_keyboard",
    "get_main_menu_keyboard",
    "get_recipe_view_keyboard",
    "get_recipes_list_keyboard",
    "get_search_menu_keyboard",
    "get_search_results_keyboard",
    "get_subcategories_keyboard",
    "get_top_categories_keyboard",
]
